import '@mantine/core/styles.css';
import '@mantine/dates/styles.css';
import { ColorSchemeScript, createTheme, MantineColorsTuple, MantineProvider } from "@mantine/core";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const memoryAlley: MantineColorsTuple = [
  '#ffe8e8',
  '#ffcfd0',
  '#ff9b9f',
  '#ff646a',
  '#ff696e',
  '#ff696e',
  '#ff696e',
  '#ff696e',
  '#ff696e',
  '#ff696e'
];

const theme = createTheme({
  colors: {
    memoryAlley
  },
  headings: { fontFamily: 'Lato, sans-serif' },
  primaryColor: "memoryAlley"
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
      <MantineProvider theme={theme}>
        {children}
      </MantineProvider>
      </body>
    </html>
  );
}
